import { ClienteFornecedor, ClienteDependente } from './cliente-fornecedor';

export type Associado = {
  id: number;
  nome_guerra: string;
  matricula: string;
  falecido: boolean;
  falecido_serv: boolean;
  clifor_id: number;
  id_banco: number;
  dt_associacao: Date;
  dt_inicio_licenca: Date;
  dt_fim_licenca: Date;
  statusAssociado: string;
  motivoInativacao: string;
  id_opm: number;
  gerar_carteira: string;
  dt_geracao_carteira: Date;
  dt_validade_carteira: Date;
  segunda_via_carteira: string;
  status_carteira: string;
  login: string;
  senha: string;
  agencia: string;
  conta: string;
  vinculo: string;
  status_saldo: string;
  anexo: string;
  observacao: string;
  corporacao: string;
};

export type CliForAssociados = {
  id: number;
  nome: string;
  cnpjcpf: string;
  ufcobranca: string;
  ufclifor: string;
  endereco: string;
  bairro: string;
  refbancaria: string;
  refcomercial: string;
  refpessoal: string;
  endercobranca: string;
  refseproc: string;
  bairrocobranca: string;
  flagavisarvcto: boolean;
  perdesconto: number;
  dtrevisaocadastral: Date;
  dtcadastro: Date;
  fonefax: string;
  fone1: string;
  fone2: string;
  fonecelular: string;
  numcartaomag: string;
  diavencimento: number;
  vallimitecredito: number;
  vallimiteconvenio: number;
  dtvalidadecartao: Date;
  tipocadastro: string;
  inscrestadual: string;
  suframa: string;
  obsgeral: string;
  senhaconvenio: number;
  placatransporte: string;
  nomefantasia: string;
  email: string;
  nomecontato1: string;
  diasentrega: number;
  tiporegimetributacao: string;
  nomecontato2: string;
  perredtributacao: number;
  diasprazo: number;
  cepcobranca: number;
  tipofisicajuridica: string;
  perdescontogeral: number;
  diasprazo1: number;
  flagfretecif: boolean;
  diasprazo2: number;
  diasprazo3: number;
  diasprazo4: number;
  flaginativo: boolean;
  valfaturamento: number;
  flagnaoconschqserasa: boolean;
  dtultimaalteracao: Date;
  dtinicialpromocao: Date;
  dtfinalpromocao: Date;
  tiporegimetribfederal: string;
  flagpontua: boolean;
  perdescbaixaduplantecip: number;
  peracrescimooverp: number;
  url: string;
  dtcanccontrato: Date;
  flagcalculasubstituicao: boolean;
  flaglivrecomercio: boolean;
  flagdebitoautomaticohrs: boolean;
  scorecliente: number;
  flag_ativo: boolean;
  flagcalculasubstituicaoforauf: boolean;
  idgrupoeconomico: number;
  cnh: string;
  datavalidacnh: Date;
  cnhcategoria: string;
  foto: string;
  obsfinanceiro: string;
  city: string;
  code: string;
  nro: string;
  old_id: number;
  atividade_id: number;
  id_bairro: number;
  id_opm: number;
  id_centro_custo_plano_contas: number;
  matricula: string;
  data_nasc: Date;
  rg: string;
  emissor_rg: string;
  cpf: string;
  estado_civil: string;
  situacao: string;
  imagem: string;
  data_fal: Date;
  data_cad: Date;
  numero: string;
  cep: string;
  complemento: string;
  sexo: string;
  idsituacaosociao: number;
  associado: Associado;
};

export type RequerimentoEnvolvido = {
  requerimento_id: number;
  associado_id: number;
  dependente_id: number;
  solicitante: string;
  procurador: string;
  cpfProcurador: string;
  contatoProcurador: string;
  enderecoProcurador: string;
  email: string;
};

export type TipoAtendimentos = {
  id: number;
  descricao: string;
};

export type TipoServico = {
  id: number;
  nome: string;
};

export type RequerimentoAcompanhantes = {
  nome: string;
  rg: string;
  emissor_rg: string;
  cpf: string;
  idade: number;
  email: string;
  tipo: string;
  valor: number;
  agencia: string;
  conta: string;
};

export type RequerimentoAnexo = {
  id?: number;
  arquivo: string;
  name: string;
  size: number;
  requerimentoId?: number;
};

export type RequerimentoItems = {
  requerimento_id: number;
  fornecedor_id: number;
  requerente_id: number;
  dataInicial: Date;
  dataFinal: Date;
  horaSaida: Date;
  horaRetorno: Date;
  falecidoServico: boolean;
  dataVolta: Date;
  origemVolta: string;
  destinoVolta: string;
  obsVolta: string;
  origem: string;
  diaSemana: string;
  latOrigem: string;
  lgtOrigem: string;
  destino: string;
  latDestino: string;
  lgtDestino: string;
  tipo: string;
  tipoPassagem: string;
  tipoMedicamento: string;
  tipoEquipamento: string;
  equipamento: string;
  dataDevolucao: Date;
  dataDevolucaoEfetiva: Date;
  valorAuxilio: number;
  obs: string;
  valorPeculioBruto: number;
  valorFuneral: number;
  valorDivida: number;
  valorLiquido: number;
  valorReceber: number;
  valorSoldo: number;
  percentualDesconto: number;
  soldoDesconto: number;
};

export type Requeriment = {
  id: number;
  items: RequerimentoItems;
  envolvidos: RequerimentoEnvolvido;
  acompanhantes: RequerimentoAcompanhantes[];
  anexos: RequerimentoAnexo[];
  outros: ClienteFornecedor;
  clifor: ClienteFornecedor;
  dependente: ClienteDependente;
  tipoServico: TipoServico;
  tipo_servico_id: number;
  createdAt: Date;
  tipo: string;
  clifor_id: number;
  dependente_id: number;
  outros_id: number;
  numeroRequerimento: string;
  dueDate: Date;
  status: string;
  account_id: string;
};
